### PR TITLE
Mobile support #147

### PR DESCRIPTION
**Pull request by Kemmotar83**
Linked issue: #147 

In this pull request we tried to make minimal changes from your original code. It works but this is not the best code ever, and it needs refactoring. Your code is written for "web browser view" and naturally it's not designed for a different output type.

For mobile rendering we only need the rubrics object (the one containing data) so, in order to make few changes in _block_filtered_course_list_ class, we created a single getter method. Since the rubrics is created after calling get_content method, we call it anyway in the mobile_block_view method, even if we don't need the output content generated for the "browser view".

The other files are the ones needed for mobile rendering.

If anything is not clear, just ask.

Thanks you again for this plugin.

Giorgio

### CODE REVIEW

**Comment by kwiliarty** [comment]
Very nice! I have this working on a local dev instance and it seems to work well. I've invited other CLAMP devs to have a look, too, since ultimately this is a group project. My only personal concern at this point is that we don't have any tests backing this new code. Is that something you'd be willing/able to provide? It might be something to do as a separate issue, not least of all because I'm intending soon to move the testing from Travis to Github, but let me know your thoughts about that. Thank you so much for persevering with this. I think it's going to be a great addition.

**Comment by Kemmotar83** [comment]
Hi Kevin,

I'm sorry but we are not able to support you with mobile testing.

Giorgio

**Comment by kwiliarty** [comment]
I'll probably try my hand at it, then, but maybe not until the new year.

**Comment by kwiliarty** [comment]
I have had some successes and some set-backs.

### Successes

- I was able to see the block working in a mobile context by using the web-based version of the mobile app at https://mobileapp.moodledemo.net/ to connect to a local dev installation.
- I was able to set up mobile behat testing for a Moodle Docker environment
- I was able to write a very simple behat test that passes in my local installation

### Set-backs

- After initially working, the block is no longer appearing in the browser-based mobile app for me. I have instances of the block on the Home page, the My page and on a course page, but none of them shows up for me at this point. The browser console is not helping. I have tried tweaking several things and lots of restarting, but without success. The behat test is still passing. It may well be something about my set-up, but even so, the problem is highlighting the fact that I am not prepared to maintain this code efficiently.
- In addition, I cannot seem to get the mobile behat tests to run under Github Actions (which we are using for CI). Maybe the Moodle Plugin CI is skipping feature tests with an `@app` tag? I haven't yet found the source of that issue much less a solution. Right now the CI script seems not even to try to run the tests.

At this point I'm quite concerned about the technical debt that integrating this code seems likely incur. Since I do not do any other work with the mobile app, it's not a good match for my skill set. And unless we can cover it well in CI testing, it's going to be a problem waiting to happen. I've also talked things over with some of the other CLAMP devs, and they share these concerns. I'm sorry to say it, but taking on something that I don't really know how to or have the time to maintain properly would not be doing anyone a favor. 

The code itself seems good, as far as I can tell; the problem is the testing and maintenance.

**Comment by kwiliarty** [comment]
I'm sorry that this is not working out. I'm going to close the request for now, but please feel free to reopen it if you can provide any additional support, especially for CI testing.

**Comment by Kemmotar83** [comment]
Hi Kevin,

I'm sorry we can't help you with tests. Maybe in the future the app tests will be supported also for CI.
I'm quite sure that the "disappearing issues" could be addressed to the web-based version of the mobile app. We experienced compatibility issues also in the past, but we have deployed our fork in our test platforms and everything work fine.

Now, we'll try to keep updated our fork. Can I ask you a little favor? Can you just add the few lines of codes added in _block_filtered_course_list.php_ (_get_rubrics_ function). This will help us to maintain the fork. Otherwise, we'll patch it in the fork when you'll release new versions.

Thank you very much. Your work is really appreciated.

Giorgio

**Comment by kwiliarty** [comment]
Thanks for your understanding, Giorgio. It's helpful to know that the web client might be part of the problem. The pattern of weirdness continued after my previous post here. Now the block is appearing again, but I literally did not change a thing between then and now.

If we get to the point where we can support this with automated testing then we can think again about bringing it in. In the meantime, I'll add that method to the main module script. Seems like a good middle ground.

Cheers,
Kevin

**Pull request closed without merging**
